# Generated by Django 4.1.1 on 2022-09-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True)),
                ('date_of_inactive', models.DateTimeField(blank=True, null=True, verbose_name='Date of Inacitve')),
                ('is_student', models.BooleanField(default=False, verbose_name='Student')),
                ('is_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last Login')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
