# Generated by Django 4.0.5 on 2022-10-04 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capswebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Email must be: @plm.edu.ph', regex='^[A-Za-z0-9._%+-]+@plm.edu.ph$')], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Admin'),
        ),
    ]
