# Generated by Django 4.0.5 on 2022-10-04 15:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capswebsite', '0002_user_numberid_alter_user_email_alter_user_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='College')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='block',
            field=models.IntegerField(blank=True, null=True, verbose_name='Block'),
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10, null=True, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='user',
            name='numberID',
            field=models.IntegerField(null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Faculty ID must be entered in format: 20XXXXXXX', regex='^20\\d{7}$')], verbose_name='Number ID'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Course')),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='capswebsite.college', verbose_name='College')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='capswebsite.college', verbose_name='College'),
        ),
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='capswebsite.course', verbose_name='Course'),
        ),
    ]
