# Generated by Django 4.0.5 on 2022-10-04 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capswebsite', '0002_alter_user_email_alter_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='numberID',
            field=models.CharField(max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Faculty ID must be entered in format: 20XXXXXXX', regex='^20\\d{7}$')], verbose_name='Faculty ID'),
        ),
    ]
