# Generated by Django 4.1.2 on 2022-10-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capswebsite', '0004_user_firstname_user_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name'),
        ),
    ]
