# Generated by Django 4.1.2 on 2022-10-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capswebsite', '0006_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_answer',
            field=models.BooleanField(default=False, verbose_name='Has Answered'),
        ),
    ]
